const translations = {
    en: {
        "Profile": "Profile",
        "Language": "Language",
        "Choose the language that suits your application interface": "Choose the language that suits your application interface",
        "English": "English",
        "Arabic": "Arabic",
        "Bookmarks": "Bookmarks",
        "Page Bookmarks": "Page Bookmarks",
        "Ayah Bookmarks": "Ayah Bookmarks",
        "Ayah": "Ayah",
        "Juz": "Juz",
        "Page": "Page",
        "No page bookmarks saved": "No page bookmarks saved",
        "No Ayah bookmarks saved": "No Ayah bookmarks saved",
        "Clear Bookmarks": "Clear Bookmarks",
        "Radio": "Radio",
        "Last Read": "Last Read",
        "All Surah": "All Surah",
        "Search": "Search",
        "Number": "Number",
        "Number Of Ayahs": "Number Of Ayahs",
        "No last read ayah found": "No last read ayah found",
    },

    ar: {
        "Profile": "الملف الشخصي",
        "Language": "اللغة",
        "Choose the language that suits your application interface": "اختر اللغة التي تناسب واجهة التطبيق الخاص بك",
        "English": "الانجليزية",
        "Arabic": "العربية",
        "Bookmarks": "المفضلة",
        "Page Bookmarks": "الصفحات المفضلة",
        "Ayah Bookmarks": "الآيات المفضلة",
        "Ayah": "الآية",
        "Juz": "الجزء",
        "Page": "الصفحة",
        "No page bookmarks saved": "لا توجد صفحات مفضلة محفوظة",
        "No Ayah bookmarks saved": "لا توجد أيات مفضلة محفوظة",
        "Clear Bookmarks": "مسح المفضلات",
        "Radio": "الراديو",
        "Last Read": "أخر القراءات",
        "All Surah": "كل السور",
        "Search": "بحث",
        "Number": "الرقم",
        "Number Of Ayahs": "عدد الآيات",
        "No last read ayah found": "لم يتم العثور على أخر قراءة أية",
    }
    }
export { translations };